#!/usr/bin/php
<?php
/**
 * Created by PhpStorm.
 * User: tony
 * Date: 12/15/14
 * Time: 9:22 PM
 */


require_once 'zimbraAdmin.php';

$zm = new \zimbraAdmin('mail2.i-webb.net', 'admin@mail2.i-webb.net', '!AFtony19833');

$domains = $zm->zimbra_get_all_domains();
